#Do NOT run this to fail back operations. THERE WILL BE DATA LOSS IF YOU DO!!!
#This scipt is only meant for testing.
---
- hosts: localhost
  collections:
    - netapp.ontap
  name: test1 
  
  vars_prompt: 
    - name: host
      prompt: Host IP
      private: false
    - name: uname
      prompt: Enter username
      private: false
    - name: passw
      prompt: Enter password
     # private: false
    - name: svm
      prompt: Enter SVM name
      private: false
      
  tasks:
  - name: Check that the SVM has broken SnapMirror relationships
    na_ontap_command:
      hostname: "{{ host }}"
      username: "{{ uname }}"
      password: "{{ passw }}"
      https: true
      validate_certs: false
      command: ['snapmirror show -destination-path {{ svm }}:* -fields state']
      return_dict: true
    register: svmdrstatus
    until: svmdrstatus.msg.stdout.find("Broken-off") != -1
    retries: 5
    delay: 30
  - name: Display results
    debug:
      msg: "{{ svmdrstatus.msg.stdout_lines[2].split()[2] }}"

  - name: Command to restore borken SnapMirror relationships
    na_ontap_command:
      hostname: "{{ host }}"
      username: "{{ uname }}"
      password: "{{ passw }}"
      https: true
      validate_certs: false
      command: ['snapmirror resync -destination-path {{ svm }}:*']
  - name: command to show volume
    na_ontap_command:
      hostname: "{{ host }}"
      username: "{{ uname }}"
      password: "{{ passw }}"
      https: true
      validate_certs: false
      command: ['snapmirror show -destination-path {{ svm }}:* -fields state']
      return_dict: true
    register: svmdrstatus
    until: svmdrstatus.msg.stdout.find("Snapmirrored") != -1
    retries: 5
    delay: 30
  - name: Display results
    debug:
      msg: "{{ svmdrstatus.msg.stdout_lines[2].split()[2] }}"

